# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-31 23:04
from __future__ import unicode_literals

import Accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'A user with the email address already exists.'}, max_length=255, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(error_messages={'blank': 'Last name must be provided.'}, max_length=255, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to=Accounts.models.user_directory_path),
        ),
    ]
